import type { Theme } from "./index";

/*
 * GitHub's own colours, from Primer's functional tokens
 * (`@primer/primitives`, MIT licensed). The comments on GitHub Light name
 * the Primer token each of Verdandi's takes its colour from, and the dark
 * themes take theirs from the same ones.
 */

export const githubLight: Theme = {
  id: "github-light",
  name: "GitHub Light",
  kind: "light",
  colors: {
    background: "#ffffff", // bgColor-default
    foreground: "#1f2328", // fgColor-default
    card: "#ffffff", // bgColor-default
    "card-foreground": "#1f2328",
    popover: "#ffffff", // overlay-bgColor
    "popover-foreground": "#1f2328",
    primary: "#1f883d", // button-primary-bgColor-rest
    "primary-foreground": "#ffffff", // button-primary-fgColor-rest
    secondary: "#f6f8fa", // control-bgColor-rest
    "secondary-foreground": "#25292e", // control-fgColor-rest
    muted: "#f6f8fa", // bgColor-muted
    "muted-foreground": "#59636e", // fgColor-muted
    accent: "#818b981a", // control-transparent-bgColor-hover
    "accent-foreground": "#1f2328",
    destructive: "#d1242f", // fgColor-danger
    border: "#d1d9e0", // borderColor-default
    input: "#d1d9e0", // control-borderColor-rest
    ring: "#0969da", // focus-outlineColor
    sidebar: "#f6f8fa", // bgColor-inset
    "sidebar-foreground": "#1f2328",
    "sidebar-primary": "#0969da", // bgColor-accent-emphasis
    "sidebar-primary-foreground": "#ffffff", // fgColor-onEmphasis
    "sidebar-accent": "#818b981a", // control-transparent-bgColor-hover
    "sidebar-accent-foreground": "#1f2328",
    "sidebar-border": "#d1d9e0",
    "sidebar-ring": "#0969da",
    overlay: "#c8d1da66", // overlay-backdrop-bgColor
    "issue-open": "#1a7f37", // fgColor-open
    "issue-closed": "#8250df", // fgColor-done
    blocked: "#d1242f", // fgColor-danger
    "blocked-surface": "#ffebe9", // bgColor-danger-muted
    blocking: "#9a6700", // fgColor-attention
    warning: "#9a6700", // fgColor-attention
    selection: "#ddf4ff", // bgColor-accent-muted
    "selection-edge": "#0969da", // fgColor-accent
    "map-new": "#4ac26b66", // borderColor-success-muted
    "map-moved": "#d4a72c66", // borderColor-attention-muted
    "gh-fg-muted": "#59636e",
    "gh-accent": "#0969da",
    "gh-border": "#d1d9e0",
    "gh-border-muted": "#d1d9e0b3",
    "gh-canvas-subtle": "#f6f8fa",
    "gh-neutral-muted": "#818b981f",
    "gh-success": "#1a7f37",
    "gh-done": "#8250df",
    "gh-attention": "#9a6700",
    "gh-danger": "#d1242f",
    "pl-comment": "#59636e",
    "pl-constant": "#0550ae",
    "pl-reference-link": "#0a3069",
    "pl-entity": "#6639ba",
    "pl-storage-modifier-import": "#1f2328",
    "pl-entity-tag": "#0550ae",
    "pl-keyword": "#cf222e",
    "pl-string": "#0a3069",
    "pl-variable": "#953800",
    "pl-bracket-unmatched": "#82071e",
    "pl-bracket-angle": "#59636e",
    "pl-invalid-text": "#d1242f",
    "pl-invalid-bg": "#ffebe9",
    "pl-carriage-return-text": "#f6f8fa",
    "pl-carriage-return-bg": "#cf222e",
    "pl-string-regexp": "#116329",
    "pl-markup-list": "#3b2300",
    "pl-markup-heading": "#0550ae",
    "pl-markup-italic": "#1f2328",
    "pl-markup-bold": "#1f2328",
    "pl-markup-deleted-text": "#82071e",
    "pl-markup-deleted-bg": "#ffebe9",
    "pl-markup-inserted-text": "#116329",
    "pl-markup-inserted-bg": "#dafbe1",
    "pl-markup-changed-text": "#953800",
    "pl-markup-changed-bg": "#ffd8b5",
    "pl-markup-ignored-text": "#d1d9e0",
    "pl-markup-ignored-bg": "#0550ae",
    "pl-meta-diff-range": "#8250df",
    "pl-gutter-mark": "#818b98",
  },
};

export const githubDark: Theme = {
  id: "github-dark",
  name: "GitHub Dark",
  kind: "dark",
  colors: {
    background: "#0d1117",
    foreground: "#f0f6fc",
    card: "#0d1117",
    "card-foreground": "#f0f6fc",
    popover: "#010409",
    "popover-foreground": "#f0f6fc",
    primary: "#238636",
    "primary-foreground": "#ffffff",
    secondary: "#212830",
    "secondary-foreground": "#f0f6fc",
    muted: "#151b23",
    "muted-foreground": "#9198a1",
    accent: "#656c7633",
    "accent-foreground": "#f0f6fc",
    destructive: "#f85149",
    border: "#3d444d",
    input: "#3d444d",
    ring: "#1f6feb",
    sidebar: "#010409",
    "sidebar-foreground": "#f0f6fc",
    "sidebar-primary": "#1f6feb",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#656c7633",
    "sidebar-accent-foreground": "#f0f6fc",
    "sidebar-border": "#3d444d",
    "sidebar-ring": "#1f6feb",
    overlay: "#21283066",
    "issue-open": "#3fb950",
    "issue-closed": "#ab7df8",
    blocked: "#f85149",
    "blocked-surface": "#f851491a",
    blocking: "#d29922",
    warning: "#d29922",
    selection: "#388bfd1a",
    "selection-edge": "#4493f8",
    "map-new": "#2ea04366",
    "map-moved": "#bb800966",
    "gh-fg-muted": "#9198a1",
    "gh-accent": "#4493f8",
    "gh-border": "#3d444d",
    "gh-border-muted": "#3d444db3",
    "gh-canvas-subtle": "#151b23",
    "gh-neutral-muted": "#656c7633",
    "gh-success": "#3fb950",
    "gh-done": "#ab7df8",
    "gh-attention": "#d29922",
    "gh-danger": "#f85149",
    "pl-comment": "#9198a1",
    "pl-constant": "#79c0ff",
    "pl-reference-link": "#a5d6ff",
    "pl-entity": "#d2a8ff",
    "pl-storage-modifier-import": "#f0f6fc",
    "pl-entity-tag": "#7ee787",
    "pl-keyword": "#ff7b72",
    "pl-string": "#a5d6ff",
    "pl-variable": "#ffa657",
    "pl-bracket-unmatched": "#f85149",
    "pl-bracket-angle": "#9198a1",
    "pl-invalid-text": "#f85149",
    "pl-invalid-bg": "#f851491a",
    "pl-carriage-return-text": "#f0f6fc",
    "pl-carriage-return-bg": "#b62324",
    "pl-string-regexp": "#7ee787",
    "pl-markup-list": "#f2cc60",
    "pl-markup-heading": "#1f6feb",
    "pl-markup-italic": "#f0f6fc",
    "pl-markup-bold": "#f0f6fc",
    "pl-markup-deleted-text": "#ffdcd7",
    "pl-markup-deleted-bg": "#67060c",
    "pl-markup-inserted-text": "#aff5b4",
    "pl-markup-inserted-bg": "#033a16",
    "pl-markup-changed-text": "#ffdfb6",
    "pl-markup-changed-bg": "#5a1e02",
    "pl-markup-ignored-text": "#f0f6fc",
    "pl-markup-ignored-bg": "#1158c7",
    "pl-meta-diff-range": "#d2a8ff",
    "pl-gutter-mark": "#3d444d",
  },
};

export const githubDarkDimmed: Theme = {
  id: "github-dark-dimmed",
  name: "GitHub Dark Dimmed",
  kind: "dark",
  colors: {
    background: "#212830",
    foreground: "#d1d7e0",
    card: "#212830",
    "card-foreground": "#d1d7e0",
    popover: "#2a313c",
    "popover-foreground": "#d1d7e0",
    primary: "#347d39",
    "primary-foreground": "#ffffff",
    secondary: "#2a313c",
    "secondary-foreground": "#d1d7e0",
    muted: "#262c36",
    "muted-foreground": "#9198a1",
    accent: "#656c7626",
    "accent-foreground": "#d1d7e0",
    destructive: "#e5534b",
    border: "#3d444d",
    input: "#3d444d",
    ring: "#316dca",
    sidebar: "#151b23",
    "sidebar-foreground": "#d1d7e0",
    "sidebar-primary": "#316dca",
    "sidebar-primary-foreground": "#f0f6fc",
    "sidebar-accent": "#656c7626",
    "sidebar-accent-foreground": "#d1d7e0",
    "sidebar-border": "#3d444d",
    "sidebar-ring": "#316dca",
    overlay: "#262c3666",
    "issue-open": "#57ab5a",
    "issue-closed": "#986ee2",
    blocked: "#e5534b",
    "blocked-surface": "#e5534b1a",
    blocking: "#c69026",
    warning: "#c69026",
    selection: "#4184e41a",
    "selection-edge": "#478be6",
    "map-new": "#46954a66",
    "map-moved": "#ae7c1466",
    "gh-fg-muted": "#9198a1",
    "gh-accent": "#478be6",
    "gh-border": "#3d444d",
    "gh-border-muted": "#3d444db3",
    "gh-canvas-subtle": "#262c36",
    "gh-neutral-muted": "#656c7633",
    "gh-success": "#57ab5a",
    "gh-done": "#986ee2",
    "gh-attention": "#c69026",
    "gh-danger": "#e5534b",
    "pl-comment": "#9198a1",
    "pl-constant": "#6cb6ff",
    "pl-reference-link": "#96d0ff",
    "pl-entity": "#dcbdfb",
    "pl-storage-modifier-import": "#f0f6fc",
    "pl-entity-tag": "#8ddb8c",
    "pl-keyword": "#f47067",
    "pl-string": "#96d0ff",
    "pl-variable": "#f69d50",
    "pl-bracket-unmatched": "#e5534b",
    "pl-bracket-angle": "#9198a1",
    "pl-invalid-text": "#e5534b",
    "pl-invalid-bg": "#e5534b1a",
    "pl-carriage-return-text": "#f0f6fc",
    "pl-carriage-return-bg": "#ad2e2c",
    "pl-string-regexp": "#8ddb8c",
    "pl-markup-list": "#eac55f",
    "pl-markup-heading": "#316dca",
    "pl-markup-italic": "#f0f6fc",
    "pl-markup-bold": "#f0f6fc",
    "pl-markup-deleted-text": "#ffd8d3",
    "pl-markup-deleted-bg": "#78191b",
    "pl-markup-inserted-text": "#b4f1b4",
    "pl-markup-inserted-bg": "#1b4721",
    "pl-markup-changed-text": "#ffddb0",
    "pl-markup-changed-bg": "#682d0f",
    "pl-markup-ignored-text": "#f0f6fc",
    "pl-markup-ignored-bg": "#255ab2",
    "pl-meta-diff-range": "#dcbdfb",
    "pl-gutter-mark": "#3d444d",
  },
};
